#!/bin/bash

set -euo pipefail

[[ "$PROCEDUREKIT_HASH" == "change-me" ]] && echo "You need to set \$PROCEDUREKIT_HASH" && exit 1

echo "--- :git: Updating submodule"

echo "cd sources/ProcedureKit"
cd "sources/ProcedureKit"

echo "git fetch origin"
git fetch origin

echo "git checkout $PROCEDUREKIT_HASH"
git checkout $PROCEDUREKIT_HASH

echo "cd ../.."
cd "../.."

echo "bundle install --quiet"
bundle install --quiet

echo "--- Jazzy ProcedureKit"

echo "cd sources/ProcedureKit"
cd "sources/ProcedureKit"

echo "bundle exec jazzy --clean --output docs --config .jazzy.json"
bundle exec jazzy --clean --output docs --config .jazzy.json

echo "--- :aws: Upload"
echo 'aws s3 sync docs "s3://procedure.kit.run/$PROCEDUREKIT_BRANCH" --acl public-read --delete'
aws s3 sync docs "s3://procedure.kit.run/$PROCEDUREKIT_BRANCH" --acl public-read --delete
