#!/bin/bash

set -euo pipefail

[[ "$PROCEDUREKIT_HASH" == "change-me" ]] && echo "You need to set \$PROCEDUREKIT_HASH" && exit 1

echo "--- :git: Updating submodule"

echo "cd sources/ProcedureKit"
cd "sources/ProcedureKit"

echo "git fetch origin"
git fetch origin

echo "git checkout $PROCEDUREKIT_HASH"
git checkout $PROCEDUREKIT_HASH

echo "cd ../.."
cd "../.."

echo "bundle install --quiet"
bundle install --quiet

echo "--- Jazzy"
bundle exec jazzy --config jazzy.json

echo "--- Upload"
buildkite-agent artifact upload "docs/**/*" s3://procedure.kit.run/development
